feature/#38 refactor LoginActivity on Kotlin
8pade8/PasswordSaver pull request #21
Opened 2020-07-17 16:11 UTC by cillywilly

2020-07-19 17:34 UTC, boJlek requested changes
Исправь

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +    private var preferencesEditor: SharedPreferences.Editor? = null
для всех переменных , кроме attemt, используй lateinit var. и не нужны будут ? и null

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +import android.preference.PreferenceManager
используй androidx

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        if (security?.password?.isEmpty()!!) {
убрать ? и !!

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        preferencesEditor = preferences?.edit()
убрать ?

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        if (preferences?.contains(ATTEMPT_COUNT)!!) {
убрать ? и !!

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +            attemptPassword = preferences?.getInt(ATTEMPT_COUNT, 0)!!
убрать ? и !!

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        if (security!!.password != passwordIn!!.text.toString()) {
убрать !!

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +            passwordIn!!.setText("")
убрать !!

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +            val blockTime = preferences!!.getLong("blockTime", 0)
убрать !!

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        preferencesEditor!!.apply()
убрать !!

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        preferencesEditor!!.apply()
убрать !!

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +    fun openAddUserActivity(view: View?) {
для таких методов используй аннотацию:
@Suppress("UNUSED_PARAMETER")
fun....{
}

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +    private val crypto = true //Определеят шифровать ли данные, задел на будущее
верни строки к остальным)

2020-07-19 17:34 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +class LoginActivity : AppCompatActivity() {
пустую строку

2020-07-23 13:06 UTC, 8pade8 requested changes

2020-07-23 13:06 UTC, 8pade8 commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.java
> +//}
зачем этот файл? удали

2020-07-23 13:06 UTC, 8pade8 commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        passwordIn = findViewById(R.id.password)
используй binding

2020-07-23 13:06 UTC, 8pade8 commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        super.onCreate(savedInstanceState)
вынеси инициализацию полей в отдельный метод

2020-07-23 13:06 UTC, 8pade8 commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        preferences = PreferenceManager.getDefaultSharedPreferences(this)
вместо Депрекейтед методов используй методы из библиотеки androidx, как уже написал bojlek

2020-07-23 13:06 UTC, 8pade8 commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +    fun openAddUserActivity(view: View?) {
сделать метод private

2020-07-27 08:11 UTC, cillywilly commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        passwordIn = findViewById(R.id.password)
видит бог я пытался, ниче не получилось. сдаюсь

2020-07-28 19:17 UTC, boJlek requested changes

2020-07-28 19:17 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +    private lateinit  var preferencesEditor: SharedPreferences.Editor
после изменений кода пользуйся ctrl+alt+L для форматирования кода

2020-07-28 19:17 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +
лишняя строка

2020-07-28 19:17 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +        startActivity(openAddUserActivity)
сделай проще: startActivity(Intent(this, AddUserActivity::class.java)).
переменная нигде больше не используется - значит не нужна.

2020-07-28 19:17 UTC, boJlek commented on app/src/main/java/net/a8pade8/passwordsaver/activities/LoginActivity.kt
> +            startActivity(openMainActivity)
смотри выше комментарий

2020-07-31 15:18 UTC, boJlek approved these changes

2020-08-23 15:33 UTC, 8pade8 approved these changes

2020-08-23 15:33 UTC, merged